### ISSUE TITLE
Nu apare deloc index

### ISSUE THREAD

**Issue by ciubix2000** [cnecrea/eonromania#3]
2025-01-01 19:59:00.677 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "default_config". Check lines 2 and 5
2025-01-01 19:59:00.733 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration fusion_solar which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-01-01 19:59:00.734 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-01-01 19:59:00.734 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-01-01 19:59:00.735 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration shelly which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-01-01 19:59:00.735 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration google_photos which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-01-01 19:59:00.736 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration google_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-01-01 19:59:00.736 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration midea_ac which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-01-01 19:59:00.737 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration huawei_solar which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-01-01 19:59:00.737 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration eonromania which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-01-01 19:59:00.737 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration auto_backup which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-01-01 19:59:00.738 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hikvision_next which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-01-01 19:59:00.738 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration zha_toolkit which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-01-01 19:59:00.739 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-01-01 19:59:04.075 WARNING (MainThread) [homeassistant.config_entries] Config entry 'gabi.ciubotaru@yahoo.com' for tuya integration could not authenticate: Authentication failed. Please re-authenticate
2025-01-01 19:59:04.561 DEBUG (MainThread) [custom_components.eonromania] Inițializarea integrării eonromania
2025-01-01 19:59:04.561 DEBUG (MainThread) [custom_components.eonromania] Configurarea intrării pentru eonromania
2025-01-01 19:59:04.565 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'eonromania' accesses hass.helpers.aiohttp_client, which should be updated to import functions used from aiohttp_client directly at custom_components/eonromania/__init__.py, line 194: session = hass.helpers.aiohttp_client.async_get_clientsession(). This will stop working in Home Assistant 2025.5, please create a bug report at https://github.com/cnecrea/eonromania/issues
2025-01-01 19:59:04.612 WARNING (MainThread) [py.warnings] <unknown>:2: SyntaxWarning: invalid escape sequence '\?'

2025-01-01 19:59:04.613 WARNING (MainThread) [py.warnings] <unknown>:1: SyntaxWarning: invalid escape sequence '\?'

2025-01-01 19:59:04.610 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up fusion_solar platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/fusion_solar/sensor.py", line 807, in async_setup_entry
    kiosk = FusionSolarKiosk(kioskConfig[CONF_URL], kioskConfig[CONF_NAME])
  File "/config/custom_components/fusion_solar/fusion_solar/kiosk/kiosk.py", line 13, in __init__
    self._parseId()
    ~~~~~~~~~~~~~^^
  File "/config/custom_components/fusion_solar/fusion_solar/kiosk/kiosk.py", line 16, in _parseId
    id = re.search("\?kk=(.*)", self.url).group(1)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'
2025-01-01 19:59:05.233 DEBUG (MainThread) [custom_components.eonromania] Token obținut dinamic: c0368551-46df-4c4c-9f16-98ad92172669
2025-01-01 19:59:05.522 DEBUG (MainThread) [custom_components.eonromania] Finished fetching eonromania_dateuser_coordinator data in 0.960 seconds (success: True)
2025-01-01 19:59:05.988 DEBUG (MainThread) [custom_components.eonromania] Token obținut dinamic: c0368551-46df-4c4c-9f16-98ad92172669
2025-01-01 19:59:06.181 DEBUG (MainThread) [custom_components.eonromania] Răspuns API pentru URL_CITIREINDEX: {'readingPeriod': {'startDate': '2025-01-20', 'endDate': '2025-01-28', 'startDateDistributor': '2025-01-20', 'endDateDistributor': '2025-01-28', 'allowedReading': True, 'allowChange': True, 'hasReadingCommand': False, 'smartDevice': True, 'distributorType': None, 'invoiceRequested': None, 'accountContract': '002202885936', 'annualConvention': None, 'currentReadingType': '01', 'hasDifferentDeviceInstalled': None, 'billingPortion': None, 'disconnectionStatus': None, 'inPeriod': False}, 'indexDetails': {'devices': []}}
2025-01-01 19:59:06.181 DEBUG (MainThread) [custom_components.eonromania] Finished fetching eonromania_citireindex_coordinator data in 0.659 seconds (success: True)
2025-01-01 19:59:06.654 DEBUG (MainThread) [custom_components.eonromania] Token obținut dinamic: c0368551-46df-4c4c-9f16-98ad92172669
2025-01-01 19:59:07.050 DEBUG (MainThread) [custom_components.eonromania] Răspuns API pentru URL_ARHIVA: {'history': [{'year': 2024, 'meters': [{'meterSeries': '001009183002001746', 'indexes': [{'indexType': 'R', 'readings': [{'month': 10, 'value': 11329.79, 'readingType': '01', 'decimals': 3}, {'month': 9, 'value': 11033.789, 'readingType': '01', 'decimals': 3}, {'month': 9, 'value': 11140.992, 'readingType': '01', 'decimals': 3}, {'month': 8, 'value': 11026.639, 'readingType': '01', 'decimals': 3}, {'month': 7, 'value': 10918.837, 'readingType': '01', 'decimals': 3}, {'month': 6, 'value': 10770.329, 'readingType': '01', 'decimals': 3}, {'month': 5, 'value': 10584.252, 'readingType': '01', 'decimals': 3}, {'month': 4, 'value': 9778.123, 'readingType': '03', 'decimals': 3}, {'month': 3, 'value': 9658.123, 'readingType': '03', 'decimals': 3}, {'month': 2, 'value': 9538.123, 'readingType': '03', 'decimals': 3}, {'month': 1, 'value': 9418.123, 'readingType': '03', 'decimals': 3}]}]}]}, {'year': 2023, 'meters': [{'meterSeries': '001009183002001746', 'indexes': [{'indexType': 'R', 'readings': [{'month': 12, 'value': 9209.123, 'readingType': '01', 'decimals': 3}, {'month': 11, 'value': 9128.309, 'readingType': '01', 'decimals': 3}, {'month': 10, 'value': 8780.452, 'readingType': '01', 'decimals': 3}, {'month': 9, 'value': 8686.055, 'readingType': '01', 'decimals': 3}, {'month': 8, 'value': 8612.856, 'readingType': '01', 'decimals': 3}, {'month': 7, 'value': 8510.658, 'readingType': '01', 'decimals': 3}, {'month': 6, 'value': 8443.762, 'readingType': '01', 'decimals': 3}, {'month': 5, 'value': 8374.703, 'readingType': '01', 'decimals': 3}, {'month': 4, 'value': 8280.63, 'readingType': '01', 'decimals': 3}, {'month': 3, 'value': 8145.915, 'readingType': '01', 'decimals': 3}, {'month': 2, 'value': 8023.469, 'readingType': '01', 'decimals': 3}, {'month': 1, 'value': 7827.818, 'readingType': '01', 'decimals': 3}]}]}]}, {'year': 2022, 'meters': [{'meterSeries': '001009183002001746', 'indexes': [{'indexType': 'R', 'readings': [{'month': 12, 'value': 7595.726, 'readingType': '01', 'decimals': 3}, {'month': 11, 'value': 7375.585, 'readingType': '01', 'decimals': 3}, {'month': 10, 'value': 7190.595, 'readingType': '01', 'decimals': 3}, {'month': 9, 'value': 7099.889, 'readingType': '01', 'decimals': 3}, {'month': 8, 'value': 7036.306, 'readingType': '01', 'decimals': 3}, {'month': 7, 'value': 7021.034, 'readingType': '01', 'decimals': 3}, {'month': 6, 'value': 7003.706, 'readingType': '01', 'decimals': 3}, {'month': 5, 'value': 7003.368, 'readingType': '01', 'decimals': 3}, {'month': 4, 'value': 7003.197, 'readingType': '01', 'decimals': 3}, {'month': 3, 'value': 6966.993, 'readingType': '01', 'decimals': 3}, {'month': 2, 'value': 6891.205, 'readingType': '01', 'decimals': 3}, {'month': 1, 'value': 6657.129, 'readingType': '01', 'decimals': 3}]}]}]}, {'year': 2021, 'meters': [{'meterSeries': '001009183002001746', 'indexes': [{'indexType': 'R', 'readings': [{'month': 12, 'value': 6399.76, 'readingType': '01', 'decimals': 3}, {'month': 11, 'value': 6153.426, 'readingType': '01', 'decimals': 3}, {'month': 9, 'value': 5768.478, 'readingType': '01', 'decimals': 3}, {'month': 8, 'value': 5641.553, 'readingType': '01', 'decimals': 3}, {'month': 7, 'value': 5384.133, 'readingType': '01', 'decimals': 3}, {'month': 6, 'value': 5064.445, 'readingType': '01', 'decimals': 3}, {'month': 5, 'value': 4830.204, 'readingType': '01', 'decimals': 3}, {'month': 4, 'value': 4617.902, 'readingType': '01', 'decimals': 3}, {'month': 3, 'value': 4394.212, 'readingType': '01', 'decimals': 3}, {'month': 2, 'value': 4137.458, 'readingType': '01', 'decimals': 3}]}]}]}]}
2025-01-01 19:59:07.050 DEBUG (MainThread) [custom_components.eonromania] Finished fetching eonromania_arhiva_coordinator data in 0.869 seconds (success: True)
2025-01-01 19:59:07.522 DEBUG (MainThread) [custom_components.eonromania] Token obținut dinamic: c0368551-46df-4c4c-9f16-98ad92172669
2025-01-01 19:59:07.692 DEBUG (MainThread) [custom_components.eonromania] Răspuns API pentru URL_FACTURASOLD: {'balance': 0, 'refund': False, 'date': '01.01.2025', 'refundInProcess': False, 'refundRequestCreatedAt': None, 'hasGuarantee': False, 'hasUnpaidGuarantee': False, 'balancePay': False}
2025-01-01 19:59:07.692 DEBUG (MainThread) [custom_components.eonromania] Finished fetching eonromania_facturasold_coordinator data in 0.642 seconds (success: True)
2025-01-01 19:59:07.692 DEBUG (MainThread) [custom_components.eonromania] Pregătire pentru forward platform setup pentru 01JGHENW5HACZEJKC98QCRE061
2025-01-01 19:59:07.695 DEBUG (MainThread) [custom_components.eonromania.sensor] Inițializare DateContractSensor: name=Date contract, unique_id=eonromania_date_contract_01JGHENW5HACZEJKC98QCRE061
2025-01-01 19:59:07.695 DEBUG (MainThread) [custom_components.eonromania.sensor] Dispozitive detectate în citireindex_data: []
2025-01-01 19:59:07.695 DEBUG (MainThread) [custom_components.eonromania.sensor] Inițializare ArhivaSensor: name=Arhivă - 2024, unique_id=eonromania_arhiva_01JGHENW5HACZEJKC98QCRE061_2024, year=2024
2025-01-01 19:59:07.695 DEBUG (MainThread) [custom_components.eonromania.sensor] Inițializare ArhivaSensor: name=Arhivă - 2023, unique_id=eonromania_arhiva_01JGHENW5HACZEJKC98QCRE061_2023, year=2023
2025-01-01 19:59:07.696 DEBUG (MainThread) [custom_components.eonromania.sensor] Inițializare ArhivaSensor: name=Arhivă - 2022, unique_id=eonromania_arhiva_01JGHENW5HACZEJKC98QCRE061_2022, year=2022
2025-01-01 19:59:07.696 DEBUG (MainThread) [custom_components.eonromania.sensor] Inițializare ArhivaSensor: name=Arhivă - 2021, unique_id=eonromania_arhiva_01JGHENW5HACZEJKC98QCRE061_2021, year=2021
2025-01-01 19:59:07.696 DEBUG (MainThread) [custom_components.eonromania.sensor] Senzor DateContractSensor - Starea datelor pe senzor: 002202885936
2025-01-01 19:59:07.696 DEBUG (MainThread) [custom_components.eonromania.sensor] Senzor DateContractSensor - Atribute: {'Cod încasare': '002202885936', 'Cod loc de consum (NLC)': '5003336251', 'CLC - Cod punct de măsură': 'EMO3526847', 'Operator de Distribuție (OD)': 'DELGAZ GRID S.A.', 'Preț final (fără TVA)': '1.09333 lei', 'Preț final (cu TVA)': '1.30106 lei', 'Preț furnizare': '0.66129 lei/kWh', 'Tarif reglementat distribuție': '0.30246 lei/kWh', 'Tarif reglementat transport': '0.04305 lei/kWh', 'PCS': '10.657', 'Adresă consum': 'Strada Stefan cel Mare 148 ap. , Siretu (Letea Veche)', 'Următoarea verificare a instalației': None, 'Data inițierii reviziei': '2025-01-10', 'Următoarea revizie tehnică': None}
2025-01-01 19:59:07.696 DEBUG (MainThread) [custom_components.eonromania.sensor] Senzor ArhivaSensor - Atribute generate: {'Index octombrie': 11329, 'Metodă de citire octombrie': 'Citire distribuitor', 'Index septembrie': 11140, 'Metodă de citire septembrie': 'Citire distribuitor', 'Index august': 11026, 'Metodă de citire august': 'Citire distribuitor', 'Index iulie': 10918, 'Metodă de citire iulie': 'Citire distribuitor', 'Index iunie': 10770, 'Metodă de citire iunie': 'Citire distribuitor', 'Index mai': 10584, 'Metodă de citire mai': 'Citire distribuitor', 'Index aprilie': 9778, 'Metodă de citire aprilie': 'Estimare', 'Index martie': 9658, 'Metodă de citire martie': 'Estimare', 'Index februarie': 9538, 'Metodă de citire februarie': 'Estimare', 'Index ianuarie': 9418, 'Metodă de citire ianuarie': 'Estimare'}
2025-01-01 19:59:07.697 DEBUG (MainThread) [custom_components.eonromania.sensor] Senzor ArhivaSensor - Atribute generate: {'Index decembrie': 9209, 'Metodă de citire decembrie': 'Citire distribuitor', 'Index noiembrie': 9128, 'Metodă de citire noiembrie': 'Citire distribuitor', 'Index octombrie': 8780, 'Metodă de citire octombrie': 'Citire distribuitor', 'Index septembrie': 8686, 'Metodă de citire septembrie': 'Citire distribuitor', 'Index august': 8612, 'Metodă de citire august': 'Citire distribuitor', 'Index iulie': 8510, 'Metodă de citire iulie': 'Citire distribuitor', 'Index iunie': 8443, 'Metodă de citire iunie': 'Citire distribuitor', 'Index mai': 8374, 'Metodă de citire mai': 'Citire distribuitor', 'Index aprilie': 8280, 'Metodă de citire aprilie': 'Citire distribuitor', 'Index martie': 8145, 'Metodă de citire martie': 'Citire distribuitor', 'Index februarie': 8023, 'Metodă de citire februarie': 'Citire distribuitor', 'Index ianuarie': 7827, 'Metodă de citire ianuarie': 'Citire distribuitor'}
2025-01-01 19:59:07.697 DEBUG (MainThread) [custom_components.eonromania.sensor] Senzor ArhivaSensor - Atribute generate: {'Index decembrie': 7595, 'Metodă de citire decembrie': 'Citire distribuitor', 'Index noiembrie': 7375, 'Metodă de citire noiembrie': 'Citire distribuitor', 'Index octombrie': 7190, 'Metodă de citire octombrie': 'Citire distribuitor', 'Index septembrie': 7099, 'Metodă de citire septembrie': 'Citire distribuitor', 'Index august': 7036, 'Metodă de citire august': 'Citire distribuitor', 'Index iulie': 7021, 'Metodă de citire iulie': 'Citire distribuitor', 'Index iunie': 7003, 'Metodă de citire iunie': 'Citire distribuitor', 'Index mai': 7003, 'Metodă de citire mai': 'Citire distribuitor', 'Index aprilie': 7003, 'Metodă de citire aprilie': 'Citire distribuitor', 'Index martie': 6966, 'Metodă de citire martie': 'Citire distribuitor', 'Index februarie': 6891, 'Metodă de citire februarie': 'Citire distribuitor', 'Index ianuarie': 6657, 'Metodă de citire ianuarie': 'Citire distribuitor'}
2025-01-01 19:59:07.697 DEBUG (MainThread) [custom_components.eonromania.sensor] Senzor ArhivaSensor - Atribute generate: {'Index decembrie': 6399, 'Metodă de citire decembrie': 'Citire distribuitor', 'Index noiembrie': 6153, 'Metodă de citire noiembrie': 'Citire distribuitor', 'Index septembrie': 5768, 'Metodă de citire septembrie': 'Citire distribuitor', 'Index august': 5641, 'Metodă de citire august': 'Citire distribuitor', 'Index iulie': 5384, 'Metodă de citire iulie': 'Citire distribuitor', 'Index iunie': 5064, 'Metodă de citire iunie': 'Citire distribuitor', 'Index mai': 4830, 'Metodă de citire mai': 'Citire distribuitor', 'Index aprilie': 4617, 'Metodă de citire aprilie': 'Citire distribuitor', 'Index martie': 4394, 'Metodă de citire martie': 'Citire distribuitor', 'Index februarie': 4137, 'Metodă de citire februarie': 'Citire distribuitor'}
2025-01-01 19:59:07.697 DEBUG (MainThread) [custom_components.eonromania] Forward platform setup complet pentru 01JGHENW5HACZEJKC98QCRE061

**Comment by cnecrea** [comment]
Salut, la mulți ani!

Da, începând de la ora 00:00 de astăzi, indexul este în curs de actualizare și nu este disponibil pe platforma E.ON. Aceasta nu reprezintă o eroare a integrării.


---

💡 **Ți-a fost de folos răspunsul sau integrarea?**  
☕ Susține acest proiect și invită-mă la o cafea: [buymeacoffee.com/cnecrea](https://buymeacoffee.com/cnecrea)

Mulțumesc! 🙏

---

**Comment by cnecrea** [comment]
Doar ca să fii la curent: azi am terminat de corectat integrarea și erorile cunoscute. Cel mai probabil, azi și/sau mâine o să fac un debug ca să mă asigur că totul e în regulă, iar apoi o să public un release.

Mulțumesc pentru răbdare! 🙏

---
### ☕ Susține dezvoltatorul

Dacă ți-a plăcut această integrare și vrei să sprijini munca depusă, **invită-mă la o cafea**! 🫶  
Nu costă nimic, iar contribuția ta ajută la dezvoltarea viitoare a proiectului. 🙌  

[![Buy Me A Coffee](https://img.shields.io/badge/Buy%20Me%20A%20Coffee-Susține%20dezvoltatorul-orange?style=for-the-badge&logo=buy-me-a-coffee)](https://buymeacoffee.com/cnecrea)

Mulțumesc pentru sprijin și apreciez fiecare gest de susținere! 🤗
